export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};
import '@/styles/reset.css';
import '@/styles/globals.css';
import { ReactNode } from 'react';
import { UserInfoProvider } from '@/contexts/UserInfoContext';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';

interface LayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang='en'>
      <head>
        <title>My App</title>
      </head>
      <body>
        <UserInfoProvider>
          <Header />
          {children}
          <Footer />
        </UserInfoProvider>
      </body>
    </html>
  );
}
